GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9lIiwiaWF0IjoxNzA4NjMyNzg1LCJleHAiOjE3MDg2MzI4MDB9.a54d5CkaSyHFjdRAbHOcHlXstq9C872gw6WjL0wheGw
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "name": "test",
    "email": "e"
}

###
post http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9lIiwiaWF0IjoxNzA4NjMyOTczfQ.jd-5Biu1-QSCY69zcfZSaPYA4MLC8C-MRkWy8xSMheE"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "Joe",
    "password": "123"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "e",
    "password": "123"
}

###

POST http://localhost:4000/register
Content-Type: application/json

{
    "name": "test",
    "email": "e",
    "password": "123",
    "password_confirm": "123"
}

###

DELETE http://localhost:4000/account/delete
Content-Type: application/json

{
    "email": "e"
}